{{- if .use_secrets }}

# Default TOML configuration file

# Whether to log to a file or not
log_to_file = false

# Languages to keep (list of ISO 639-1 codes)
keep_languages = ["en"]

# External services used to determine the original language of a movie or TV show
radarr_api_key = "{{- onepasswordRead .secrets.radarr_api_key }}"
radarr_url     = "{{- onepasswordRead .secrets.radarr_url }}"
sonarr_api_key = "{{- onepasswordRead .secrets.sonarr_api_key }}"
sonarr_url     = "{{- onepasswordRead .secrets.sonarr_url }}"
tmdb_api_key   = "{{- onepasswordRead .secrets.tmdb_api_key }}"

{{- end }}
