#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
[ -z "$PS1" ] && return

# set default umask
umask 002

# Build PATH and put /usr/local/bin before existing PATH
export PATH="/usr/local/bin:$PATH:$HOME/bin"

### SOURCE BASH PLUGINS ###

# Locations containing files *.bash to be sourced to your environment
bashFileLocations=(
  ${HOME}/dotfiles/config/bash
  ${HOME}/dotfiles-private/config/bash
  )

for bashFileLocation in "${bashFileLocations[@]}"; do
  if [ -d "${bashFileLocation}" ]; then
    for config_file in ${bashFileLocation}/*.bash; do
      if [ -f "${config_file}" ]; then
        source "${config_file}"
      fi
    done
  fi
done

# Always list directory contents upon 'cd'.
# (Somehow this always failed when I put it in a sourced file)
cd() { builtin cd "$@"; ll ; }

# RVM complains if it's not here
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting

