schemaVersion = 1

[extensions]
enabledIdentifiers = [ 'com.brnbw.tuna.plugins.github' ]

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[hotkeys.app.textMode]
carbonKeyCode = 49
carbonModifiers = 2304

[[hotkeys.custom]]
id = 'FBC5A754-FEBB-46E1-9D29-06B3C1253D3D'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'Tuna.Internal.ClipboardProxyCatalog.Clipboard History'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 42
    carbonModifiers = 2304

[[leaderMode.bindings]]
key = 's'
url = 'tuna://run/path.%252FApplications%252FSafari.app/Open'

[[leaderMode.bindings]]
key = 'f'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
key = 'm'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[leaderMode.bindings]]
key = 'd'
url = 'tuna://run/path.%252FUsers%252Fnatelandau%252FDownloads/Open'

[[leaderMode.bindings]]
key = 'h'
url = 'tuna://run/path.%252FUsers%252Fnatelandau/Open'

[settings]
clipboardIgnoredBundleIdentifiers = [ 'org.mozilla.librewolf' ]
themeIdentifier = 'com.brnbw.tuna.themes.NormieBar'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'
