[documents]
    git_stop_words = "op://yc7nim47s6rch4ehrvfsz5icei/vgapmuu57fs3ic44wyupk2orgi/notesPlain"

[secrets]
    ansible_vault_password       = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/ansible_vault_password"
    bws_zoom_address             = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/bws_zoom_link"
    calendly_address             = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/calendly"
    email_address                = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/default_email"
    gitea_address                = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/gitea_url"
    github_personal_access_token = "op://igqbsqdriuefyzvljd7pom5tum/ikd4inhzvm5pvo2bkyrnkuobh4/personal_access_token"
    gitleaks_password_regex      = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/gitleaks_password_regex"
    gitleaks_pii_regex           = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/gitleaks_pii_regex"
    homebrew_github_token        = "op://igqbsqdriuefyzvljd7pom5tum/ikd4inhzvm5pvo2bkyrnkuobh4/homebrew_access_token"
    radarr_api_key               = "op://igqbsqdriuefyzvljd7pom5tum/yevda4magqej3yawqf573rijd4/api_key"
    radarr_url                   = "op://igqbsqdriuefyzvljd7pom5tum/yevda4magqej3yawqf573rijd4/website"
    sonarr_api_key               = "op://igqbsqdriuefyzvljd7pom5tum/5zk3pkmm2wbk73ss4dlli6dvz4/api_key"
    sonarr_url                   = "op://igqbsqdriuefyzvljd7pom5tum/5zk3pkmm2wbk73ss4dlli6dvz4/website"
    tmdb_api_key                 = "op://igqbsqdriuefyzvljd7pom5tum/7l5gtxkd23og5wzawz5etq6lju/api_key"
    valentina_github_token       = "op://igqbsqdriuefyzvljd7pom5tum/ikd4inhzvm5pvo2bkyrnkuobh4/valentina_access_token"
    zoom_address                 = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/zoom_link"
