[documents]
    git_stop_words = "op://yc7nim47s6rch4ehrvfsz5icei/vgapmuu57fs3ic44wyupk2orgi/notesPlain"

[secrets]
    gitea_address = "op://yc7nim47s6rch4ehrvfsz5icei/chxkudodrzwfuuq42m4cjrnp7y/URL"
