# Configuration for brewup

# Target location for Applications, mimics --appdird.
# app_dir          = ""

exclude_updades = [
    "1password",
    "arq",
    "discord",
    "docker",
    "docker-compose",
    "fmail2",
    "fork",
    "mongodb-compass",
    "raycast",
    "syncthing",
    "visual-studio-code",
    "zoom",
]

# List of packages to exclude from updates
# Update all casks, even if they auto-update
greedy_casks = false

# Full path to `brew` if not in $PATH
# homebrew_command = ""

# List of casks to open after updating
reopen_casks = ["iterm2", "raycast", "slack", "syncthing"]

# List of casks to unquarantine after updating
no_quarantine = ["librewolf"]
